name: Github actions for Front End PR's and Pushes

on:
  push:
    branches: [main]
    paths:
      - "blog-app/**"
  pull_request:
    branches: [main]
    paths:
      - "blog-app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./blog-app/"
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  # Updated Node.js versions

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: Build npm project
        run: npm run build --if-present
      # - name: Run test cases
      #   run: npm test
      # env:
      #   CI: true
      - name: Install Jest
        run: npm i -g jest
      - name: Run tests
        run: jest -u --config ./jest.config.js --coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: blog-app  # Updated to match directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
